name: Test

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  cross:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        arch:
          - mingw

    container:
      image: debian:bullseye
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install deps
        run: HOST=${{ matrix.arch }} sh .ci/deps.sh

      - name: Prepare the system
        run: HOST=${{ matrix.arch }} sh .ci/test/prepare.sh

      - name: Run tests with default settings
        run: sudo -u build CI=1 HOST=${{ matrix.arch }} sh .ci/test/run.sh default

      - name: Run tests without legacy protocol
        run: sudo -u build CI=1 HOST=${{ matrix.arch }} sh .ci/test/run.sh nolegacy
        if: always()

      - name: Run tests with libgcrypt
        run: sudo -u build CI=1 HOST=${{ matrix.arch }} sh .ci/test/run.sh gcrypt
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_cross_${{ matrix.arch }}
          path: /tmp/logs/tests.*.tar.gz
        if: always()
        
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu:20.04
    container:
      image: ${{ matrix.os }}
      options: --privileged
      env:
        CI: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install deps
        run: sh .ci/deps.sh

      - name: Assign name for test results artifact
        run: echo ARTIFACT="$(echo '${{ matrix.os }}' | sed 's|[:/]|_|g')" >>"$GITHUB_ENV"

      - name: Create a non-privileged user
        run: sh .ci/test/prepare.sh

      - name: Run tests with OpenSSL 3
        run: sudo -u build CI=1 sh .ci/test/run.sh openssl3

      - name: Run tests with default settings
        run: sudo -u build CI=1 sh .ci/test/run.sh default
        if: always()

      - name: Run tests without legacy protocol
        run: sudo -u build CI=1 sh .ci/test/run.sh nolegacy
        if: always()

      - name: Run tests with libgcrypt
        run: sudo -u build CI=1 sh .ci/test/run.sh gcrypt
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_${{ env.ARTIFACT }}
          path: /tmp/logs/tests.*.tar.gz
        if: always()

      - name: Build package
        run: sh .ci/package/build.sh
        if: github.ref == 'refs/heads/1.1' || startsWith(github.ref, 'refs/tags/release-')
        continue-on-error: true

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: pkg-${{ env.ARTIFACT }}
          path: |
            *.deb
            ~/rpmbuild/RPMS/*/*.rpm
        continue-on-error: true

  pkg-publish:
    if: always() && (github.ref == 'refs/heads/1.1' || startsWith(github.ref, 'refs/tags/release-'))
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - linux
      - mingw

    steps:
      - name: Create artifact directory
        run: mkdir -p /tmp/artifacts

      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          path: /tmp/artifacts

      - name: Publish packages (dev)
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          title: Development release
          prerelease: true
          files: /tmp/artifacts/**/*.(deb|rpm|exe)
        if: startsWith(github.ref, 'refs/heads/')

      - name: Publish packages (release)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/artifacts/**/*.deb
            /tmp/artifacts/**/*.rpm
            /tmp/artifacts/**/*.exe
        if: startsWith(github.ref, 'refs/tags/')

  mingw:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          # https://packages.msys2.org/package/
          install: >-
            base-devel
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-libgcrypt
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-lzo2
            mingw-w64-x86_64-lz4
            mingw-w64-x86_64-ncurses
            mingw-w64-x86_64-miniupnpc
            mingw-w64-x86_64-nsis
            git
            openbsd-netcat
            procps

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run tests with default settings
        shell: msys2 {0}
        run: sh .ci/test/run.sh default

      - name: Create installer
        shell: msys2 {0}
        run: sh .ci/package/build.sh
        if: github.ref == 'refs/heads/1.1' || startsWith(github.ref, 'refs/tags/release-')
        continue-on-error: true

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: pkg-windows
          path: .ci/package/win/tinc-*.exe
        continue-on-error: true

      - name: Run tests without legacy protocol
        shell: msys2 {0}
        run: sh .ci/test/run.sh nolegacy
        if: always()

      - name: Run tests with libgcrypt
        shell: msys2 {0}
        run: sh .ci/test/run.sh gcrypt
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_windows
          path: /tmp/logs/tests.*.tar.gz
        if: always()
